export const SET_APPLICATION_REQUEST_SUBMITTED = 'landingPage/SET_APPLICATION_REQUEST_SUBMITTED';
export const SET_APPLICATION_RESPONSE_RECEIVED = 'landingPage/SET_APPLICATION_RESPONSE_RECEIVED';
export const SET_NEW_ACCOUNT_REQUEST_SUBMITTED = 'newAccount/SET_NEW_ACCOUNT_REQUEST_SUBMITTED';
export const SET_NEW_ACCOUNT_RESPONSE_RECEIVED = 'newAccount/SET_NEW_ACCOUNT_RESPONSE_RECEIVED';
