POST http://localhost:8080/request HTTP/1.1
content-type: application/json

{
  "body": "hello world"
}

###

POST http://localhost:8080/callback/1 HTTP/1.1

###

PUT http://localhost:8080/callback/1 HTTP/1.1
content-type: application/json

{
  "status": "hello world",
  "detail": "foo bar"
}

###

GET http://localhost:8080/status/1 HTTP/1.1
content-type: application/json
