POST http://localhost:8080/request HTTP/1.1
content-type: application/json

{
  "body": "body goes here"
}

###

POST http://localhost:8080/callback/{{$dotenv ID}} HTTP/1.1

###

PUT http://localhost:8080/callback/{{$dotenv ID}} HTTP/1.1
content-type: application/json

{
  "status": "PROCESSED",
  "detail": "detail goes here"
}

###

GET http://localhost:8080/status/{{$dotenv ID}} HTTP/1.1

###

GET http://localhost:8080/dump HTTP/1.1

